name: glowup-db-backups
schedule:
  frequency: daily
  time: "02:00 UTC"
retention:
  daily: 7
  weekly: 4
  monthly: 3
storage:
  type: spaces
  region: nyc3
  bucket: glowup-backups
notifications:
  email:
    recipients:
      - admin@glowup.app
    on_success: true
    on_failure: true
backup_type: full
compression: true
encryption: true 