name: Azure Production Deployment

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: glowup-app
  AZURE_RESOURCE_GROUP: glowup-production
  AZURE_LOCATION: East US
  AZURE_APP_SERVICE_PLAN: glowup-plan
  AZURE_REGISTRY_NAME: glowupregistry

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.AZURE_REGISTRY_NAME }}.azurecr.io/glowup:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.AZURE_REGISTRY_NAME }}.azurecr.io/glowup:latest

    - name: Run database migrations
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --settings @azure-settings.json
        azureSubscription: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: '{"text":"Production deployed to Azure: ${{ github.sha }}"}' 
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PRODUCTION }} 